name: Labs delete
on: delete
env:
  DOCKER_IMAGE: ghcr.io/navikt/sykmeldinger:${{ github.sha }}
  branchname: ${{ github.event.ref }}
jobs:
  deploy-branch-to-labs-gcp:
    if: startsWith(github.event.ref, 'labs')
    name: Delete branch labs-gcp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: gacts/github-slug@v1
        id: slug
        with:
          to-slug: sykmeldinger-${{ github.ref_name }}
      - uses: nais/deploy/actions/deploy@v1
      - name: Scale down labs-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: labs-gcp
          RESOURCE: nais-labs-branch.yaml
          VAR: image=${{ env.DOCKER_IMAGE }},appname=${{ steps.slug.outputs.slug }},replicas=0,branchState=deleted
